import type { Metadata } from "next";
// import "../../app/globals.css";
import { MobileNav } from "./components/MobileNav";
import { Sidebar } from "./components/Sidebar";
import { ThemeProvider } from "./components/ThemeProvider";
import { QueryProvider } from "./components/QueryProvider";

export const metadata: Metadata = {
  title: "invite",
  description: "Generated by invite",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider
      attribute={"class"}
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
      <QueryProvider>
        <main className="flex gap-3 h-screen dark:bg-black mx-auto w-full max-w-screen-2xl p-1 bg-slate-100 overflow-x-hidden">
          <Sidebar />
          <div className=" p-1 w-full bg-white dark:bg-black dark:base-shadow-pure-white shadow-[0px_2px_3px_-1px_rgba(0,0,0,0.1),0px_1px_0px_0px_rgba(25,28,33,0.02),0px_0px_0px_1px_rgba(25,28,33,0.08)]">
            <div className="lg:hidden">
              <MobileNav />
            </div>
            {children}
          </div>
        </main>
      </QueryProvider>
    </ThemeProvider>
  );
}
