import type { Metadata } from "next";
// import "../../app/globals.css";
import { Header } from "../(home)/components/Header";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "invite",
  description: "Generated by invite",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-slate-100 text-black dark:bg-black dark:text-white">
      <SessionProvider>
        <Header disableAnimation={true} disableLoginButton={true} />
        {children}
      </SessionProvider>
    </div>
  );
}
