import { ImageKitProvider } from "@imagekit/next";
import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import "./globals.css";

export const metadata: Metadata = {
  title: "10MinDesign",
  description: "Generated by 10MinDesign",
  icons: {
    icon: "/logo-bg.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function () {
                try {
                  const theme = localStorage.getItem('theme');
                  if (
                    theme === 'dark' ||
                    (!theme && window.matchMedia('(prefers-color-scheme: dark)').matches)
                  ) {
                    document.documentElement.classList.add('dark');
                  } else {
                    document.documentElement.classList.remove('dark');
                  }
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body className="bg-slate-100 text-black dark:bg-black dark:text-white">
        <ImageKitProvider urlEndpoint={process.env.imagekit_URL}>
          {children}
          <ToastContainer />
        </ImageKitProvider>
      </body>
    </html>
  );
}
