FROM node:22-alpine

RUN npm install -g pnpm
RUN npm install -g turbo

WORKDIR /app

COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/backend-auth ./apps/backend-auth

# COPY . .

RUN pnpm install 
RUN pnpm run db:generate
RUN pnpm run build

EXPOSE 8080

CMD ["pnpm","start:backend"]