FROM node:22-alpine

RUN npm install -g pnpm
RUN npm install -g turbo

WORKDIR /app

COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web/

# COPY . .

RUN pnpm install 
RUN pnpm run build

EXPOSE 3000

CMD ["pnpm","start:web"]