FROM node:22-alpine AS base
RUN apk update
RUN apk add --no-cache libc6-compat
# Set working directory
RUN npm install -g pnpm
RUN npm install -g turbo
WORKDIR /app
 
# ---
FROM base AS prepare


COPY . .
RUN turbo prune web --docker
 

FROM base AS builder
COPY --from=prepare /app/out/json/ .
RUN pnpm install
COPY --from=prepare /app/out/full/ .
 
RUN pnpm turbo build
 

FROM base AS runner
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
USER nextjs
 
COPY --from=builder --chown=nextjs:nodejs /app/apps/web/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/web/.next/static ./apps/web/.next/static
COPY --from=builder --chown=nextjs:nodejs /app/apps/web/public ./apps/web/public
 
CMD ["node", "apps/web/server.js"]